### ISSUE TITLE
Icon compilation

### ISSUE THREAD

**Issue by mattlima** [mattlima/wp-theme-seed#5]
@gustavoelizalde does the SVG icon compilation function we borrowed from the A17 repo still work on this version?

**Comment by gustavoelizalde** [comment]
hey @mattlima, I run a test and I see it's working normally. 

Testing branch 'master'

**Comment by mattlima** [comment]
Cool, thanks @gustavoelizalde. @mikejoyceio you can incorporate this for future SVG icon stuff.
